GPIO_VOLUME_INC = 13
GPIO_VOLUME_DEC = 19

GPIO_SPEED_INC = 26
GPIO_SPEED_DEC = 21

GPIO_PLAY_START_STOP = 20
GPIO_FORWARD = 16
GPIO_BACKWARD = 12

GPIO_BATTERY_LEVEL = 7
GPIO_CAPTURE = 6
GPIO_CANCEL = 5


GPIO_LIGHT = 25

# GPIO_ON_OFF = 3 # Uncatchable

CONFIG_FILE = "config.json"

DELAY_TO_SAVE = 10

DEFAUL_SETTINGS = {'volume': 50,
                   'speed' : 110,
                   'voice' : 'mb/mb-fr4'}
